- name: Get slave status from slaves
  mysql_replication:
    login_port: "{{ login_port }}"
    login_user: root
    login_password: "{{ root_password }}"
    login_unix_socket: "{{ socket }}"
    mode: getslave
  register: status

- debug:
    msg:
      - "Slave_SQL_Running is:{{ status | json_query(\"Slave_SQL_Running\") }}"
      - "Slave_IO_Running is: {{ status | json_query(\"Slave_IO_Running\") }}"
      - "Seconds_Behind_Master is: {{ status | json_query(\"Seconds_Behind_Master\") }}"
      - "Last_Error is: {{ status | json_query(\"Last_Error\") }}"
      - "Master_Host is: {{ status | json_query(\"Master_Host\") }}"

