---
# tasks file for manage_mysql
- include: password.yml

- include: system_check.yml

- include: mysql_info.yml
  when: gather_information | default(False)

- include: manage_variables.yml
  when: manage_mysql | default(False)

- include: manage_replication.yml
  when: manage_slave | default(False)