- name: Backing up the original my.cnf
  copy:
    src: "{{ etcdir }}/my.cnf"
    dest: "{{ etcdir }}/myback.cnf"
    owner: mysql
    group: mysql
    mode: 0644
    backup: yes
    remote_src: yes

- name: Rendering mysql parameter file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: mysql
    group: mysql
    mode: 0644
  with_items:
    - { src: 'my.cnf.j2', dest: "{{ etcdir }}/my.cnf" }

- name: Rendering bash file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0744
  with_items:
    - { src: 'my.cnf_auto.sh.j2', dest: "{{ etcdir }}/my.cnf_auto.sh" }

- name: Auto config my.cnf
  shell: "sh -x {{ etcdir }}/my.cnf_auto.sh"

- name: Remove my.cnf_auto.sh
  file:
    path: "{{ etcdir }}/my.cnf_auto.sh"
    state: absent
    remote_src: yes