# Add or remove MySQL databases from a remote host

- name: Dump multiple databases
  mysql_db:
    login_host: localhost
    login_user: root
    login_password: "{{ root_password }}"
    login_port: "{{ login_port }}"
    login_unix_socket: "{{ socket }}"
    state: dump
    quick: yes
    single_transaction: yes
    name: "{{ dump_dbname }}"
    target: "{{ dump_target }}"