- name: Restore database
  mysql_db:
    login_user: root
    login_password: "{{ root_password }}"
    login_port: "{{ login_port }}"
    login_unix_socket: "{{ socket }}"
    name: all
    state: import
    target: "{{ import_target }}"
  when: import_target is defined
