# Manage MySQL global variables
- name: Check for global variables
  mysql_variables:
    login_user: root
    login_password: "{{ root_password }}"
    login_port: "{{ login_port }}"
    login_unix_socket: "{{ socket }}"
    variable: "{{ variable }}"
  register: mysql_variable

- name: Get MySQL variable for human read
  debug:
    msg: "The {{ variable }} of {{ ansible_hostname }} is: {{ mysql_variable | json_query(\"msg\") }}"

- name: Set global variables value
  mysql_variables:
    login_user: root
    login_password: "{{ root_password }}"
    login_port: "{{ login_port }}"
    login_unix_socket: "{{ socket }}"
    variable: "{{ item.variable }}"
    value: "{{ item.value | string }}"
  with_items: "{{ variable_value }}"
  when: modify_variable_value