# Add or remove MySQL databases from a remote host

- name: Dump multiple databases
  mysql_db:
    login_user: root
    login_password: "{{ root_password }}"
    login_port: "{{ login_port }}"
    login_unix_socket: "{{ socket }}"
    state: dump
    quick: yes
    single_transaction: yes
    name: "{{ dump_dbname }}"
    target: "{{ dump_target }}"
  when: dump_target is defined

- name: Restore database
  mysql_db:
    login_user: root
    login_password: "{{ root_password }}"
    login_port: "{{ login_port }}"
    login_unix_socket: "{{ socket }}"
    name: all
    state: import
    target: "{{ import_target }}"
  when: import_target is defined
